### ISSUE TITLE
TypeError: unhashable type: 'list' when creating table with fks

### ISSUE THREAD

**Issue by Chris2L** [AnswerDotAI/sqlite-minutils#2]
I'm using fasthtml with fastlite wrapper with this code:
```
from fasthtml.common import *

db = database('data/test.db')

authors = db.t.authors
if authors not in db.t:
    authors.create(id=int, name=str, pk='id')
    authors.create_index(columns=['name'], unique=True)
Author = authors.dataclass()

books = db.t.books
if books not in db.t:
    books.create(id=int, title=str, book_uid=str, author_fk=int, pk='id', foreign_keys=[('author_fk', 'authors', 'id')])
Book = books.dataclass()
```
When calling books.create, it ends up in sqlite_minutils/db.py in class Database's def create_table.  After calling `self.execute(sql)` it tries to call `self.table(....)` to return the newly created table.  It fails here with error `TypeError: unhashable type: 'list'`.  
- If I remove all kwargs and leave name only, it works fine.  
- If I make it `foreign_keys=None` instead of `foreign_keys=foreign_keys` it works fine.

I can't seem to place the origin of the error.  If it was type setting then it should have failed at `sql = self.create_table_sql`.

Any advice?

**Comment by jph00** [comment]
I think this is fixed now - please reopen if I'm wrong.

**Comment by Chris2L** [comment]
Iv'e run 
```
pip install -U sqlite-minutils
```
and it is now on version 3.37.0.post1 and  I still get the error

**Comment by jph00** [comment]
Actually sorry just realised there hadn't been a release since it was fixed. Just did one, so please re-check.

**Comment by Chris2L** [comment]
Resolved thank you
